### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [hizzlekizzle/RetroArch-AppImage#1]
Thanks for making an AppImage, we'd like to add it to appimage.github.io. However it does not run on Ubuntu xenial because it was compiled on too new a system:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-9143/AppRun)
```

Can you please fix it? Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2135

**Comment by hizzlekizzle** [comment]
@probonopd How about this: https://github.com/hizzlekizzle/RetroArch-AppImage/releases/tag/Linux_LTS_Nightlies

That one is built from Xenial, so it should work for LTS purposes and we can keep that other build around for bleeding-edge purposes.

**Comment by probonopd** [comment]
Thanks @hizzlekizzle. I am sure that you are aware that the one built on xenial should also run on newer distributions? So I am not sure what you mean by "bleeding-edge purposes".

In any case, this one passes the test. Thank you very much! :+1:

**Comment by hizzlekizzle** [comment]
>I am sure that you are aware that the one built on xenial should also run on newer distributions?

Yes, it runs, but the same glibcxx mismatch happens with a few of the libretro cores that we distribute from our buildbot.

**Comment by hizzlekizzle** [comment]
@probonopd I'm going to be retiring this repo/build soon, as we now have official appimages building on our homegrown CI system. What do I need to do to get appimage.github.io pointing to our new builds? We have amd64 builds [here](http://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z) and 32-bit builds [here](http://buildbot.libretro.com/nightly/linux/x86/RetroArch.7z). They're built on bionic, but I figured that would be okay, since everything is dropping xenial this month.
